name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'jaunger'

inputs:
  github_token:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  openai_api_key:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  issue_label:
    description: 'The label assigned to GitHub issues that should be processed by the AutoCoder action. Only issues with this label will trigger the code generation process.'
    required: true
    default: 'autocoder-bot'
  repository:
    description: 'The repository where the action will be executed.'
    required: true
  issue_number:
    description: 'The number of the issue that triggered the action.'
    required: true
  script_path:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: true
    default: './scripts/script.sh'

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'
    value: ${{ steps.create_pr.outputs.pull_request_url }}

runs:
  using: 'composite'
  steps:
    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash

    - name: Generate Code from Issue
      run: |
        chmod +x "${{ inputs.script_path }}"
        bash "${{ inputs.script_path }}" "${{ inputs.github_token }}" "${{ inputs.repository }}" "${{ inputs.issue_number }}" "${{ inputs.openai_api_key }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}

    - name: Commit Generated Code
      run: |
        git config --global user.name "autocoder-bot"
        git config --global user.email "autocoder-bot@users.noreply.github.com"
        git add .
        git commit -m "feat: add new auto-generated code" || echo "No changes to commit"
      shell: bash

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: autocoder-branch-${{ inputs.issue_number }}
        base: main
        title: "AutoCoder: Generated code for issue #${{ inputs.issue_number }}"
        labels: ${{ inputs.issue_label }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
