name: 'AutoCoder'
description: 'A reusable GitHub Action that uses OpenAI ChatGPT to generate code from GitHub issues and automatically create a pull request with the generated code.'
author: 'Your Name or Organization'

# Define the inputs your action requires
inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true

  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true

  REPOSITORY:
    description: 'The repository where the action will be executed (e.g., user/repo).'
    required: true

  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true

  SCRIPT_PATH:
    description: 'Path to the script that interacts with ChatGPT and generates code (e.g., scripts/generate_code.py).'
    required: true

  LABEL:
    description: 'The label that triggers this action. Only issues with this label will be processed.'
    required: false
    default: 'autocoder'

# Optional outputs (example: pull request URL)
outputs:
  pull_request_url:
    description: 'The URL of the pull request created with the generated code.'
    value: ${{ steps.create_pr.outputs.pull_request_url }}

# Define how the action runs
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python (if your generator script uses Python)
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: ${{ inputs.SCRIPT_PATH && endsWith(inputs.SCRIPT_PATH, '.py') }}
      run: |
        pip install -r requirements.txt || true
      shell: bash

    - name: Generate code from issue using ChatGPT
      run: |
        echo "🚀 Running AutoCoder script..."
        python "${{ inputs.SCRIPT_PATH }}" \
          --repo "${{ inputs.REPOSITORY }}" \
          --issue "${{ inputs.ISSUE_NUMBER }}" \
          --label "${{ inputs.LABEL }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}

    - name: Create Pull Request with generated code
      id: create_pr
      run: |
        echo "📦 Creating pull request..."
        gh pr create \
          --repo "${{ inputs.REPOSITORY }}" \
          --head "autocoder/${{ inputs.ISSUE_NUMBER }}" \
          --base main \
          --title "Auto-generated code for issue #${{ inputs.ISSUE_NUMBER }}" \
          --body "This pull request was automatically generated by AutoCoder."
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

# Optional branding section (for marketplace)
branding:
  icon: 'cpu'
  color: 'blue'
