name: 'AutoCoder'
description: 'Automates code generation from GitHub issues using OpenAI’s ChatGPT and creates a pull request for review.'
author: 'Your Name or Organization'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  REPOSITORY:
    description: 'The repository where the action will be executed.'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with ChatGPT to generate code from issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'Path to the script that interacts with ChatGPT and generates code.'
    required: true
    default: './scripts/script.sh'
  LABEL:
    description: 'Label that triggers the AutoCoder action.'
    required: false
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'The URL of the pull request automatically created with the generated code.'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Fix line endings (convert CRLF to LF)
      run: sed -i 's/\r$//' ${{ inputs.SCRIPT_PATH }}
      shell: bash

    - name: Make script executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}
      shell: bash

    - name: Run AutoCoder script
      id: generate_code
      run: ${{ inputs.SCRIPT_PATH }} "${{ inputs.GITHUB_TOKEN }}" "${{ inputs.REPOSITORY }}" "${{ inputs.ISSUE_NUMBER }}" "${{ inputs.OPENAI_API_KEY }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}

    # ✅ Explicitly configure Git credentials
    - name: Configure Git credentials
      run: |
        git config --global user.name "autocoder-bot"
        git config --global user.email "actions@github.com"
      shell: bash

    # ✅ Explicitly commit generated code
    - name: Commit generated files
      run: |
        git add .
        git commit -m "feat: add new Auto generated Code" || echo "No changes to commit."
      shell: bash

    # ✅ Create PR using peter-evans/create-pull-request
    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        base: main
        title: "autocoder-branch-#${{ inputs.ISSUE_NUMBER }}"
        labels: ${{ inputs.LABEL }}

    # ✅ Output PR URL for feedback
    - name: Output Pull Request URL
      run: echo "pull_request_url=${{ steps.create_pr.outputs.pull_request_url }}" >> $GITHUB_OUTPUT
      shell: bash
