name: 'AutoCoder'
description: 'This action automates code generation from GitHub issues using OpenAI’s ChatGPT and creates a pull request with the generated code for review.'
author: 'jaunger'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. Required to create pull requests and manage repository operations.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling ChatGPT-based code generation from issue descriptions.'
    required: true
  LABEL:
    description: 'Label assigned to issues that should trigger AutoCoder. Only issues with this label are processed.'
    required: true
    default: 'autocoder-bot'
  REPOSITORY:
    description: 'The repository where the action will execute.'
    required: true
  ISSUE_NUMBER:
    description: 'The issue number that triggered this action.'
    required: true
  SCRIPT_PATH:
    description: 'Path to the script that interacts with ChatGPT and generates code.'
    required: true
    default: './scripts/script.sh'

outputs:
  pull_request_url:
    description: 'URL of the pull request containing auto-generated code for review.'
    value: ${{ steps.create_pr.outputs.pull_request_url }}

runs:
  using: 'composite'
  steps:

    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Greet User
      run: echo "👋 Hello! AutoCoder is generating code for issue #${{ inputs.ISSUE_NUMBER }}."
      shell: bash

    - name: Generate Code from Issue
      run: |
        chmod +x "${{ inputs.SCRIPT_PATH }}"
        bash "${{ inputs.SCRIPT_PATH }}" \
          "${{ inputs.GITHUB_TOKEN }}" \
          "${{ inputs.REPOSITORY }}" \
          "${{ inputs.ISSUE_NUMBER }}" \
          "${{ inputs.OPENAI_API_KEY }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}

    - name: Configure Git Credentials
      run: |
        git config --global user.name "autocoder-bot"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ inputs.GITHUB_TOKEN }}@github.com/${{ inputs.REPOSITORY }}.git
      shell: bash

    - name: Commit Generated Changes
      run: |
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "AutoCoder: Generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        fi
      shell: bash

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        base: main
        title: "AutoCoder: Generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        labels: ${{ inputs.LABEL }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

