name: "AutoCoder"
description: "Automatically generate code from GitHub issues using OpenAI's ChatGPT and create a pull request with the results."
author: "Your Name or Organization"

branding:
  icon: "robot"
  color: "blue"

inputs:
  github_token:
    description: "Personal access token used for GitHub API authentication."
    required: true
  openai_api_key:
    description: "API key for OpenAI to generate code based on issue descriptions."
    required: true
  repository:
    description: "Repository in the format owner/repo where code will be generated."
    required: true
  issue_number:
    description: "The issue number that triggered the action."
    required: true
  script_path:
    description: "Path to the shell script that interacts with ChatGPT."
    required: true
    default: "./scripts/script.sh"
  label:
    description: "The label that triggers code generation."
    required: true
    default: "autocoder-bot"

outputs:
  pull_request_url:
    description: "URL of the pull request created by the action."

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: "Ensure script is executable"
      run: chmod +x ${{ inputs.SCRIPT_PATH }}

    - name: "Run AutoCoder Script"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      run: ${{ inputs.SCRIPT_PATH }} "$GITHUB_TOKEN" "${{ inputs.REPOSITORY }}" "${{ inputs.ISSUE_NUMBER }}" "$OPENAI_API_KEY"

    - name: "Upload generated code artifact"
      uses: actions/upload-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-bot/

    - name: "Download artifact"
      uses: actions/download-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-artifact/

    - name: "Prepare generated code"
      run: |
        mkdir -p autocoder-generated
        cp -R autocoder-artifact/* autocoder-generated/
        echo "// Force change: $(date)" > autocoder-generated/force_change.txt

    - name: "Configure credentials and commit files"
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "autocoder-bot"
        git add .
        git commit -m "Autocoder generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        git push -f origin autocoder-branch-${{ inputs.ISSUE_NUMBER }}

    - name: "Create Pull Request"
      id: pr
      uses: peter-evans/create-pull-request@v5
      with:
        title: "Autocoder generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        branch: "autocoder-branch-${{ inputs.ISSUE_NUMBER }}"
        base: main
        labels: ${{ inputs.LABEL }}
        author: "autocoder-bot <actions@github.com>"
        committer: "autocoder-bot <actions@github.com>"

    - name: "Set output PR URL"
      run: echo "PULL_REQUEST_URL=${{ steps.pr.outputs.pull-request-url }}" >> $GITHUB_OUTPUT
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3
