name: 'AutoCoder'
description: 'Automates code generation from GitHub issues using OpenAI’s ChatGPT and creates a pull request for review.'
author: 'Your Name or Organization'

inputs:
  github_token:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  openai_api_key:
    description: 'API key for OpenAI, enabling interactions with ChatGPT to generate code from issue descriptions.'
    required: true
  repository:
    description: 'The GitHub repository where the action will run, e.g. user/repo.'
    required: true
  issue_number:
    description: 'The number of the issue that triggered the AutoCoder action.'
    required: true
  script_path:
    description: 'Path to the script that handles ChatGPT code generation and repository interactions.'
    required: true
    default: './scripts/script.sh'
  label:
    description: 'Label that triggers the AutoCoder process.'
    required: false
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'The URL of the pull request automatically created with the generated code.'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Ensure LF line endings
      run: sed -i 's/\r$//' ${{ inputs.script_path }}
      shell: bash

    - name: Make script executable
      run: chmod +x ${{ inputs.script_path }}
      shell: bash

    - name: Run AutoCoder script
      id: generate_code
      run: ${{ inputs.script_path }} "${{ inputs.github_token }}" "${{ inputs.repository }}" "${{ inputs.issue_number }}" "${{ inputs.openai_api_key }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}

    - name: Configure Git user
      run: |
        git config user.name "autocoder-bot"
        git config user.email "actions@github.com"
      shell: bash

    - name: Commit generated code
      run: |
        git add .
        git commit -m "feat: add new Auto generated Code" || echo "No changes to commit."
      shell: bash

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.github_token }}
        branch: autocoder-branch-${{ inputs.issue_number }}
        base: main
        title: "autocoder-branch-#${{ inputs.issue_number }}"
        labels: ${{ inputs.label }}

    - name: Output PR URL
      run: echo "pull_request_url=${{ steps.create_pr.outputs.pull_request_url }}" >> $GITHUB_OUTPUT
      shell: bash
