name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'github.com/PGSch'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  REPOSITORY:
    description: 'The repository where the action will be executed.'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: false
    default: scripts/script.sh
  LABEL:
    description: 'Label that triggers and identifies pull requests created by this action.'
    required: false
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config --local user.name "autocoder-bot"
        git config --local user.email "actions@github.com"
      shell: bash

    - name: Make script executable
      run: chmod +x ${{ github.action_path }}/${{ inputs.SCRIPT_PATH }}
      shell: bash

    - name: Generate Code with ChatGPT
      id: generate_code
      run: ${{ github.action_path }}/${{ inputs.SCRIPT_PATH }} \
        ${{ inputs.GITHUB_TOKEN }} \
        ${{ inputs.REPOSITORY }} \
        ${{ inputs.ISSUE_NUMBER }} \
        ${{ inputs.OPENAI_API_KEY }}
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-bot/

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-bot/

    - name: List Files
      run: ls -R ./autocoder-bot
      shell: bash

    - name: Configure Git credentials
      run: |
        git config --global user.name "autocoder-bot"
        git config --global user.email "actions@github.com"
      shell: bash

    - name: Commit generated code
      run: |
        git add .
        git commit -m "feat: add new Auto generated Code" 
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        labels: ${{ inputs.LABEL }}
        author: autocoder-bot <actions@github.com>
        title: "PR to issue #${{ inputs.ISSUE_NUMBER }}"
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        token: ${{ inputs.GITHUB_TOKEN }}
