name: 'AutoCoder'
description: 'A reusable GitHub Action that uses OpenAI ChatGPT to generate code from GitHub issues and automatically create a pull request with the generated code.'
author: 'Your Name or Organization'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication and pull request creation.'
    required: true

  OPENAI_API_KEY:
    description: 'API key for OpenAI to interact with ChatGPT.'
    required: true

  REPOSITORY:
    description: 'The repository where the action runs (e.g., user/repo).'
    required: true

  ISSUE_NUMBER:
    description: 'The issue number that triggered this action.'
    required: true

  SCRIPT_PATH:
    description: 'Path to the script that generates code (e.g., scripts/generate_code.sh).'
    required: true

  LABEL:
    description: 'Label that triggers the AutoCoder action.'
    required: false
    default: 'autocoder'

outputs:
  pull_request_url:
    description: 'URL of the created pull request containing the generated code.'
    value: ${{ steps.create_pr.outputs.pull-request-url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.GITHUB_TOKEN }}

    - name: Ensure script is executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}
      shell: bash

    - name: Run AutoCoder Script
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      run: ${{ inputs.SCRIPT_PATH }} "$GITHUB_TOKEN" "${{ inputs.REPOSITORY }}" "${{ inputs.ISSUE_NUMBER }}" "$OPENAI_API_KEY"
      shell: bash

    - name: Configure git credentials
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Commit generated files
      run: |
        echo "📝 Committing generated files..."
        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "AutoCoder: Generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        fi
      shell: bash

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        base: main
        title: "AutoCoder: Generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        commit-message: "AutoCoder: Generated code for issue #${{ inputs.ISSUE_NUMBER }}"
        body: "This pull request was automatically generated by AutoCoder for issue #${{ inputs.ISSUE_NUMBER }}."
        labels: ${{ inputs.LABEL }}

branding:
  icon: 'cpu'
  color: 'blue'
