name: Access Issue Information

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Fix line endings (convert CRLF to LF) 
        run: sed -i 's/\r$//' scripts/script.sh

      - name: Set permissions for script.sh
        run: chmod +x scripts/script.sh

      - name: Check if issue has 'autocoder-bot' label
        id: check_label
        run: |
          labels=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[] | .name')
          if echo "$labels" | grep -q 'autocoder-bot'; then
            echo "has_label=true" >> $GITHUB_ENV
          else
            echo "has_label=false" >> $GITHUB_ENV
          fi
      - name: Run script.sh
        if: env.has_label == 'true'
        id: generate_code
        run: bash scripts/script.sh "$GITHUB_TOKEN" "$GITHUB_REPOSITORY" "${{ github.event.issue.number }}" "$OPENAI_API_KEY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/*
          if-no-files-found: error
          retention-days: 1

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact

      - name: List files in the artifact
        run: ls -laR autocoder-bot/
