name: Auto_Coder

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  access_issue_info:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Fix line endings (convert CRLF to LF) 
        run: sed -i 's/\r$//' scripts/script.sh

      - name: Set permissions for script.sh
        run: chmod +x scripts/script.sh

      - name: Run script.sh
        id: generate_code
        run: bash scripts/script.sh "$GITHUB_TOKEN" "$GITHUB_REPOSITORY" "${{ github.event.issue.number }}" "$OPENAI_API_KEY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/*
          if-no-files-found: error
          retention-days: 1

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact

      - name: debug
        run: ls -la

      - name: List all files recursively
        run: ls -R autocoder-artifact
