name: Workflow Name
on: [push]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Greeting Message
        run: echo "Hello, world"
