name: Access Issue Information


on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  access_issue_info:
    if: contains(github.event.label.name), 'autocoder-bot')
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v5.0.0
    
      - name: Set permissions for script.sh
        run: chmod +x script.sh

      - name: Run script.sh
        id: generate_code
        run: bash script.sh "$GITHUB_TOKEN" "$GITHUB_REPOSITORY" "${{ github.event.issue.number }}" "$OPENAI_API_KEY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: autocoder-artifact 
          path: autocoder-bot/*
          if-no-files-found: error
          retention-days: 1

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: autocoder-artifact

      - name: List files in the artifact
        run: ls -laR autocoder-bot/
          
